// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: billing_service.proto
// Protobuf Java Version: 4.35.1

package billing;

@com.google.protobuf.Generated
public final class BillingServiceOuterClass extends com.google.protobuf.GeneratedFile {
  private BillingServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "BillingServiceOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BillingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BillingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BillingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BillingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025billing_service.proto\"@\n\016BillingReques" +
      "t\022\021\n\tpatientId\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005em" +
      "ail\030\003 \001(\t\"4\n\017BillingResponse\022\021\n\taccountI" +
      "d\030\001 \001(\t\022\016\n\006status\030\002 \001(\t2K\n\016BillingServic" +
      "e\0229\n\024CreateBillingAccount\022\017.BillingReque" +
      "st\032\020.BillingResponseB\013\n\007billingP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BillingRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_BillingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BillingRequest_descriptor,
        new java.lang.String[] { "PatientId", "Name", "Email", });
    internal_static_BillingResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_BillingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BillingResponse_descriptor,
        new java.lang.String[] { "AccountId", "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
