// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: billing_service.proto
// Protobuf Java Version: 4.35.1

package billing;

@com.google.protobuf.Generated
public interface BillingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BillingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountId = 1;</code>
   * @return The accountId.
   */
  java.lang.String getAccountId();
  /**
   * <code>string accountId = 1;</code>
   * @return The bytes for accountId.
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
